language: java
jdk:
- oraclejdk8
deploy:
  provider: heroku
  api_key:
    secure: U+nbezF9DiYq2Tp8BGIh2hPAv6AicNeHvDuslWXQwuuKWYA4LQY47/LGqm86i1nJN+vE6MoshOmCIHagW90cNDpo4igeknF8cYOAww4kotB/05v0trDehGfSF0sWbv81siq6A8k7I4OcxdhKKuJ/3BbEnwZ5SRCekjo2n/j0/6HCR2Qag030vdvE/gaOitj7oK6nuwSSivgofrscPIrWIWiXRezGSsMWWM85UDxGKdNDqaB3Gd7UDSc3JJAlXLH5ijS98wTful4wMaolQi4A4x9/0Y8zlR5qS1GL4OlWMMzukRGdBIAVk4aR+xZwWrI7rUOiUkLDYyqVFTuVVgornuSS/wTioFRTiL0q4N/4igkP65OXzumzOM0ZF0RfyRFn+aVwYcz14a89IbCNgTcgPM81dgWuXn3m1G8c2/CJ+Zq1VhXQFad+LHHhP1w/ruKccAj70qTnSRcqB74k/xAovggsUwTWcfmfjFrwa2UK5KzaZn6Vti4ksz4IsAlsgbkDEdjR8TxMoHqEHIqG2UluQQio7Aqyu8Vr4CUqQT1jtVRjVHjK2HHLdt06u/xf4nwO21N0YNhHus0eepHIXA1jSNlrCVcaqNK/ZWPUMoCn9g01S7dtMt9oT3RYwLl2UTGENJqBi19Wadj9Vz8mQmZuPO4EsFnFGXvBQ79fnSbHK7Q=
